# Generated by Django 2.0.1 on 2018-01-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='assistants.Assistant'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
