# Generated by Django 2.0.1 on 2018-01-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
