# Generated by Django 2.0.1 on 2018-01-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_auto_20180115_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='bio',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
