# Generated by Django 2.0.1 on 2018-01-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_assistant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
